// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBFHmqAucvh2gbbaw9L9_vnuu_dN9zoxsc',
    appId: '1:468487970493:web:28ed568c865ce00b34e1d4',
    messagingSenderId: '468487970493',
    projectId: 'hostel-connect-106e0',
    authDomain: 'hostel-connect-106e0.firebaseapp.com',
    databaseURL: 'https://hostel-connect-106e0-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'hostel-connect-106e0.appspot.com',
    measurementId: 'G-8C156WDPQP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC3B_XdjiHCz_VGSaB4zb_AXQ_APmGB2Ms',
    appId: '1:468487970493:android:131c0ab88b908a8e34e1d4',
    messagingSenderId: '468487970493',
    projectId: 'hostel-connect-106e0',
    databaseURL: 'https://hostel-connect-106e0-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'hostel-connect-106e0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCkp-yFB5FIl93p-d3A1gmOyHuQISogoCI',
    appId: '1:468487970493:ios:aecc42e4823e948034e1d4',
    messagingSenderId: '468487970493',
    projectId: 'hostel-connect-106e0',
    databaseURL: 'https://hostel-connect-106e0-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'hostel-connect-106e0.appspot.com',
    iosClientId: '468487970493-c9gv7p0vb02m4ubilsg8e6icqm1j4fuq.apps.googleusercontent.com',
    iosBundleId: 'com.example.hostelConnect',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCkp-yFB5FIl93p-d3A1gmOyHuQISogoCI',
    appId: '1:468487970493:ios:aecc42e4823e948034e1d4',
    messagingSenderId: '468487970493',
    projectId: 'hostel-connect-106e0',
    databaseURL: 'https://hostel-connect-106e0-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'hostel-connect-106e0.appspot.com',
    iosClientId: '468487970493-c9gv7p0vb02m4ubilsg8e6icqm1j4fuq.apps.googleusercontent.com',
    iosBundleId: 'com.example.hostelConnect',
  );
}
